namespace CaeriusNet.Generator.Tvp;

/// <summary>
///     Pure source emitter for <see cref="TvpModel" />. Outputs an <see cref="ITvpMapper{T}" /> implementation
///     that streams rows through a single reused <c>SqlDataRecord</c>.
/// </summary>
internal static class TvpEmitter
{
    internal static string Emit(TvpModel model)
    {
        var capacity = 600 + model.Columns.Count * 120;
        var sb = new StringBuilder(capacity);

        AppendHeader(sb);
        AppendUsings(sb);
        AppendNamespace(sb, model.Namespace);
        AppendBody(sb, model);

        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated by CaeriusNet.Generator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        sb.AppendLine();
    }

    private static void AppendUsings(StringBuilder sb)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using Microsoft.Data.SqlClient.Server;");
        sb.AppendLine("using CaeriusNet.Mappers;");
        sb.AppendLine();
    }

    private static void AppendNamespace(StringBuilder sb, string ns)
    {
        if (string.IsNullOrEmpty(ns)) return;
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
    }

    private static void AppendBody(StringBuilder sb, TvpModel model)
    {
        sb.Append("public sealed partial ").Append(model.TypeKindKeyword).Append(' ').Append(model.TypeName)
            .Append(" : ITvpMapper<").Append(model.TypeName).AppendLine(">");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>Gets the SQL Server type name for this TVP.</summary>");
        sb.Append("    public static string TvpTypeName => \"")
            .Append(model.Schema).Append('.').Append(model.TvpName).AppendLine("\";");
        sb.AppendLine();

        AppendMetaDataField(sb, model.Columns);
        AppendMapMethod(sb, model);

        sb.AppendLine("}");
    }

    private static void AppendMetaDataField(StringBuilder sb, EquatableArray<ColumnModel> columns)
    {
        sb.AppendLine("    private static readonly SqlMetaData[] _tvpMetaData =");
        sb.AppendLine("    [");

        for (var i = 0; i < columns.Count; i++)
        {
            var trailing = i < columns.Count - 1 ? "," : string.Empty;
            sb.Append("        ").Append(columns[i].SqlMetaDataConstructor).AppendLine(trailing);
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
    }

    private static void AppendMapMethod(StringBuilder sb, TvpModel model)
    {
        sb.AppendLine(
            "    /// <summary>Maps a collection of items into SQL data records for table-valued parameter usage.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveOptimization)]");
        sb.AppendLine(
            $"    [GeneratedCode(\"{GeneratedCodeInfo.ToolName}\", \"{GeneratedCodeInfo.Version}\")]");
        sb.Append("    public IEnumerable<SqlDataRecord> MapAsSqlDataRecords(IEnumerable<")
            .Append(model.TypeName).AppendLine("> items)");
        sb.AppendLine("    {");
        sb.AppendLine("        var record = new SqlDataRecord(_tvpMetaData);");
        sb.AppendLine("        foreach (var item in items)");
        sb.AppendLine("        {");

        for (var i = 0; i < model.Columns.Count; i++)
            sb.Append("            ").AppendLine(BuildSetCall(model.Columns[i]));

        sb.AppendLine("            yield return record;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    /// <summary>
    ///     Returns a single statement (terminated by <c>;</c>) that writes <c>item.{Name}</c> onto the reused
    ///     <c>SqlDataRecord</c>. Nullable parameters generate a guard that calls <c>SetDBNull</c>.
    /// </summary>
    private static string BuildSetCall(ColumnModel column)
    {
        var ordinal = column.OrdinalPosition;
        var valueAccess = column.IsNullableValueType ? ".Value" : string.Empty;
        var setMethod = column.ReaderMethod.Replace("Get", "Set");
        var assignmentTarget = $"item.{column.Name}";

        var setExpr = column.Kind switch
        {
            ColumnKind.DateOnly =>
                $"record.SetDateTime({ordinal}, {assignmentTarget}{valueAccess}.ToDateTime(global::System.TimeOnly.MinValue))",
            ColumnKind.TimeOnly =>
                $"record.SetTimeSpan({ordinal}, {assignmentTarget}{valueAccess}.ToTimeSpan())",
            ColumnKind.ByteArray =>
                $"record.SetValue({ordinal}, {assignmentTarget})",
            ColumnKind.Char =>
                $"record.SetString({ordinal}, {assignmentTarget}{valueAccess}.ToString())",
            ColumnKind.Half =>
                $"record.SetFloat({ordinal}, (float){assignmentTarget}{valueAccess})",
            ColumnKind.Enum when column.EnumUnderlyingType is not null =>
                $"record.{setMethod}({ordinal}, ({column.EnumUnderlyingType}){assignmentTarget}{valueAccess})",
            _ => $"record.{setMethod}({ordinal}, {assignmentTarget}{valueAccess})"
        };

        return column.IsNullable
            ? $"if ({assignmentTarget} is null) record.SetDBNull({ordinal}); else {setExpr};"
            : $"{setExpr};";
    }
}