namespace CaeriusNet.Generator.Tvp;

public sealed partial class TvpSourceGenerator
{
    /// <summary>
    ///     Generates and adds the <see cref="ITvpMapper{T}" /> implementation source code to the compilation.
    /// </summary>
    private static void GenerateTvpMapper(SourceProductionContext context, Metadata metadata)
    {
        var sourceCode = GenerateTvpMapperSource(metadata);
        context.AddSource($"{metadata.RecordName}.g.cs", sourceCode);
    }

    /// <summary>
    ///     Generates the complete source code for an <see cref="ITvpMapper{T}" /> implementation
    ///     that uses <see cref="SqlDataRecord" /> streaming instead of a <c>DataTable</c>.
    /// </summary>
    private static string GenerateTvpMapperSource(Metadata metadata)
    {
        var estimatedCapacity = 600 + metadata.Parameters.Count * 120;
        var sb = new StringBuilder(estimatedCapacity);

        AppendFileHeader(sb);
        AppendUsings(sb);
        AppendNamespaceStart(sb, metadata.Namespace);
        AppendClassDeclaration(sb, metadata);
        AppendTvpMetaDataField(sb, metadata);
        AppendMapAsSqlDataRecordsMethod(sb, metadata);
        AppendClassEnd(sb);
        AppendNamespaceEnd(sb, metadata.Namespace);

        return sb.ToString();
    }

    private static void AppendFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    /// <summary>
    ///     Appends the required using directives. Uses <c>System.Data</c> for
    ///     <c>SqlDbType</c> and <c>Microsoft.Data.SqlClient.Server</c> for <c>SqlDataRecord</c>/<c>SqlMetaData</c>.
    /// </summary>
    private static void AppendUsings(StringBuilder sb)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using Microsoft.Data.SqlClient.Server;");
        sb.AppendLine("using CaeriusNet.Mappers;");
        sb.AppendLine();
    }

    private static void AppendNamespaceStart(StringBuilder sb, string namespaceName)
    {
        if (string.IsNullOrEmpty(namespaceName))
            return;

        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
    }

    private static void AppendClassDeclaration(StringBuilder sb, Metadata metadata)
    {
        sb.AppendLine($"public sealed partial record {metadata.RecordName} : ITvpMapper<{metadata.RecordName}>");
        sb.AppendLine("{");

        var tvpName = GetTvpName(metadata);
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Gets the SQL Server type name for this TVP.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static string TvpTypeName => \"{tvpName}\";");
        sb.AppendLine();
    }

    /// <summary>
    ///     Emits a <c>private static readonly SqlMetaData[]</c> field that is allocated once per type.
    ///     Reusing the schema array across all invocations avoids redundant allocations.
    /// </summary>
    private static void AppendTvpMetaDataField(StringBuilder sb, Metadata metadata)
    {
        sb.AppendLine("    private static readonly SqlMetaData[] _tvpMetaData =");
        sb.AppendLine("    [");

        for (var i = 0; i < metadata.Parameters.Count; i++)
        {
            var comma = i < metadata.Parameters.Count - 1 ? "," : string.Empty;
            sb.AppendLine($"        {GetSqlMetaDataCreation(metadata.Parameters[i])}{comma}");
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
    }

    /// <summary>
    ///     Emits the <c>MapAsSqlDataRecords</c> iterator method. A single <see cref="SqlDataRecord" />
    ///     instance is reused for every row; Microsoft.Data.SqlClient reads field values before advancing
    ///     the enumerator, making this safe for TVP streaming.
    /// </summary>
    private static void AppendMapAsSqlDataRecordsMethod(StringBuilder sb, Metadata metadata)
    {
        sb.AppendLine(
            $"    public IEnumerable<SqlDataRecord> MapAsSqlDataRecords(IEnumerable<{metadata.RecordName}> items)");
        sb.AppendLine("    {");
        sb.AppendLine("        var record = new SqlDataRecord(_tvpMetaData);");
        sb.AppendLine("        foreach (var item in items)");
        sb.AppendLine("        {");

        for (var i = 0; i < metadata.Parameters.Count; i++)
            sb.AppendLine($"            {GetSetRecordCall(metadata.Parameters[i], i)}");

        sb.AppendLine("            yield return record;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void AppendClassEnd(StringBuilder sb)
    {
        sb.AppendLine("}");
    }

    private static void AppendNamespaceEnd(StringBuilder sb, string namespaceName)
    {
        // File-scoped namespaces don't require a closing brace.
    }

    /// <summary>
    ///     Returns the fully qualified TVP type name, e.g. <c>dbo.tvp_MyType</c>.
    /// </summary>
    private static string GetTvpName(Metadata metadata)
    {
        var schema = metadata.TvpSchema ?? "dbo";
        var tvpName = metadata.TvpName ?? throw new InvalidOperationException("TvpName is required");
        return $"{schema}.{tvpName}";
    }

    /// <summary>
    ///     Maps a parameter's SQL type to the appropriate <see cref="SqlMetaData" /> constructor expression.
    /// </summary>
    private static string GetSqlMetaDataCreation(ParameterMetadata parameter)
    {
        var name = parameter.Name;
        return parameter.SqlType switch
        {
            "bit" => $"new SqlMetaData(\"{name}\", SqlDbType.Bit)",
            "tinyint" => $"new SqlMetaData(\"{name}\", SqlDbType.TinyInt)",
            "smallint" => $"new SqlMetaData(\"{name}\", SqlDbType.SmallInt)",
            "int" => $"new SqlMetaData(\"{name}\", SqlDbType.Int)",
            "bigint" => $"new SqlMetaData(\"{name}\", SqlDbType.BigInt)",
            "decimal" => $"new SqlMetaData(\"{name}\", SqlDbType.Decimal, 18, 4)",
            "real" => $"new SqlMetaData(\"{name}\", SqlDbType.Real)",
            "float" => $"new SqlMetaData(\"{name}\", SqlDbType.Float)",
            "nvarchar" => $"new SqlMetaData(\"{name}\", SqlDbType.NVarChar, SqlMetaData.Max)",
            "varchar" => $"new SqlMetaData(\"{name}\", SqlDbType.VarChar, SqlMetaData.Max)",
            "nchar" => $"new SqlMetaData(\"{name}\", SqlDbType.NChar, 1)",
            "char" => $"new SqlMetaData(\"{name}\", SqlDbType.Char, 1)",
            "datetime2" => $"new SqlMetaData(\"{name}\", SqlDbType.DateTime2, 7)",
            "datetime" => $"new SqlMetaData(\"{name}\", SqlDbType.DateTime)",
            "date" => $"new SqlMetaData(\"{name}\", SqlDbType.Date)",
            "time" => $"new SqlMetaData(\"{name}\", SqlDbType.Time, 7)",
            "datetimeoffset" => $"new SqlMetaData(\"{name}\", SqlDbType.DateTimeOffset, 7)",
            "uniqueidentifier" => $"new SqlMetaData(\"{name}\", SqlDbType.UniqueIdentifier)",
            "varbinary" => $"new SqlMetaData(\"{name}\", SqlDbType.VarBinary, SqlMetaData.Max)",
            _ => $"new SqlMetaData(\"{name}\", SqlDbType.Variant)"
        };
    }

    /// <summary>
    ///     Returns a complete statement (including semicolon) that sets the value at
    ///     <paramref name="ordinal" /> on the reused <c>record</c>, handling nullability,
    ///     enum casting, char→string conversion, and special types (DateOnly, TimeOnly, byte[]).
    /// </summary>
    private static string GetSetRecordCall(ParameterMetadata parameter, int ordinal)
    {
        var isEnumType = parameter.TypeSymbol.TypeKind == TypeKind.Enum ||
                         (parameter.IsNullable &&
                          parameter.TypeSymbol is INamedTypeSymbol
                          {
                              OriginalDefinition.SpecialType: SpecialType.System_Nullable_T
                          } nullableType &&
                          nullableType.TypeArguments.Length > 0 &&
                          nullableType.TypeArguments[0].TypeKind == TypeKind.Enum);

        // .Value is needed for nullable value types to unwrap the Nullable<T>.
        var valueAccess = parameter.IsNullable && parameter.TypeSymbol.IsValueType ? ".Value" : string.Empty;

        string setExpr;

        if (parameter.RequiresSpecialConversion)
        {
            var baseType = parameter.TypeName.TrimEnd('?');
            setExpr = baseType switch
            {
                "DateOnly" or "System.DateOnly" =>
                    $"record.SetDateTime({ordinal}, item.{parameter.Name}{valueAccess}.ToDateTime(global::System.TimeOnly.MinValue))",
                "TimeOnly" or "System.TimeOnly" =>
                    $"record.SetTimeSpan({ordinal}, item.{parameter.Name}{valueAccess}.ToTimeSpan())",
                _ => // byte[] and any future special cases
                    $"record.SetValue({ordinal}, item.{parameter.Name})"
            };
        }
        else if (parameter.SqlType is "nchar" or "char")
        {
            // char has no SqlDataRecord.SetChar; convert to a one-character string.
            setExpr = $"record.SetString({ordinal}, item.{parameter.Name}{valueAccess}.ToString())";
        }
        else if (isEnumType)
        {
            var enumCast = parameter.ReaderMethod switch
            {
                "GetByte" => "(byte)",
                "GetInt16" => "(short)",
                "GetInt64" => "(long)",
                _ => "(int)"
            };
            var setMethod = parameter.ReaderMethod.Replace("Get", "Set");
            setExpr = $"record.{setMethod}({ordinal}, {enumCast}item.{parameter.Name}{valueAccess})";
        }
        else
        {
            var setMethod = parameter.ReaderMethod.Replace("Get", "Set");
            setExpr = $"record.{setMethod}({ordinal}, item.{parameter.Name}{valueAccess})";
        }

        return parameter.IsNullable
            ? $"if (item.{parameter.Name} is null) record.SetDBNull({ordinal}); else {setExpr};"
            : $"{setExpr};";
    }
}