namespace CaeriusNet.Generator.AutoContracts;

internal static class AutoContractsGeneratedSource
{
    internal static void AppendPreamble(StringBuilder sb, string @namespace)
    {
        AppendHeader(sb);
        AppendUsings(sb);
        AppendNamespace(sb, @namespace);
    }

    internal static void AppendGeneratedCodeAttribute(StringBuilder sb, string indent)
    {
        sb.Append(indent)
            .Append("[GeneratedCode(\"")
            .Append(GeneratedCodeInfo.ToolName)
            .Append("\", \"")
            .Append(GeneratedCodeInfo.Version)
            .AppendLine("\")]");
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated by CaeriusNet.Generator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        sb.AppendLine();
    }

    private static void AppendUsings(StringBuilder sb)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers.Binary;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Security.Cryptography;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CaeriusNet.Abstractions;");
        sb.AppendLine("using CaeriusNet.Attributes.AutoContracts;");
        sb.AppendLine("using CaeriusNet.Builders;");
        sb.AppendLine("using CaeriusNet.Commands.Reads;");
        sb.AppendLine("using CaeriusNet.Mappers;");
        sb.AppendLine("using Microsoft.Data.SqlClient;");
        sb.AppendLine("using Microsoft.Data.SqlClient.Server;");
        sb.AppendLine();
    }

    private static void AppendNamespace(StringBuilder sb, string ns)
    {
        if (string.IsNullOrWhiteSpace(ns))
            return;

        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
    }
}