namespace CaeriusNet.Generator.Dto;

/// <summary>
///     Pure source emitter for <see cref="DtoModel" />. Takes a fully-resolved value-equatable model and
///     produces the <see cref="ISpMapper{T}" /> implementation source — no Roslyn dependencies.
/// </summary>
internal static class DtoEmitter
{
    internal static string Emit(DtoModel model)
    {
        var capacity = 384 + model.Columns.Count * 80;
        var sb = new StringBuilder(capacity);

        sb.AppendLine("// <auto-generated by CaeriusNet.Generator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Data.SqlClient;");
        sb.AppendLine("using CaeriusNet.Mappers;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("public sealed partial ").Append(model.TypeKindKeyword).Append(' ')
            .Append(model.TypeName).Append(" : ISpMapper<").Append(model.TypeName).AppendLine(">");
        sb.AppendLine("{");
        sb.Append("    public static ").Append(model.TypeName).AppendLine(" MapFromDataReader(SqlDataReader reader)");
        sb.AppendLine("    {");
        sb.Append("        return new ").Append(model.TypeName).AppendLine("(");

        for (var i = 0; i < model.Columns.Count; i++)
        {
            var column = model.Columns[i];
            var trailing = i < model.Columns.Count - 1 ? "," : string.Empty;
            sb.Append("            ").Append(BuildReaderExpression(column)).AppendLine(trailing);
        }

        sb.AppendLine("        );");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    ///     Builds the <c>SqlDataReader</c> expression for a single column. The classification was performed
    ///     during extraction (<see cref="ColumnKind" />), so this method is a pure switch on data — no string
    ///     guessing, no <c>Contains</c>.
    /// </summary>
    private static string BuildReaderExpression(ColumnModel column)
    {
        var ordinal = column.OrdinalPosition;
        var prefix = column.IsNullable ? $"reader.IsDBNull({ordinal}) ? null : " : string.Empty;

        return column.Kind switch
        {
            ColumnKind.ByteArray => $"{prefix}(byte[])reader.GetValue({ordinal})",
            ColumnKind.DateOnly => $"{prefix}DateOnly.FromDateTime(reader.GetDateTime({ordinal}))",
            ColumnKind.TimeOnly => $"{prefix}TimeOnly.FromDateTime(reader.GetDateTime({ordinal}))",
            ColumnKind.Char => $"{prefix}reader.GetString({ordinal})[0]",
            ColumnKind.Enum => $"{prefix}({column.TypeName.TrimEnd('?')})reader.{column.ReaderMethod}({ordinal})",
            _ => $"{prefix}reader.{column.ReaderMethod}({ordinal})"
        };
    }
}
