namespace CaeriusNet.Generator.Dto;

/// <summary>
///     Pure source emitter for <see cref="DtoModel" />. Takes a fully-resolved value-equatable model and
///     produces the <see cref="ISpMapper{T}" /> implementation source — no Roslyn dependencies.
/// </summary>
internal static class DtoEmitter
{
    internal static string Emit(DtoModel model)
    {
        var useOrdinalConstants = model.Columns.Count > 8;
        var capacity = 512 + model.Columns.Count * (useOrdinalConstants ? 128 : 80);
        var sb = new StringBuilder(capacity);

        sb.AppendLine("// <auto-generated by CaeriusNet.Generator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using Microsoft.Data.SqlClient;");
        sb.AppendLine("using CaeriusNet.Mappers;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("public sealed partial ").Append(model.TypeKindKeyword).Append(' ')
            .Append(model.TypeName).Append(" : ISpMapper<").Append(model.TypeName).AppendLine(">");
        sb.AppendLine("{");

        if (useOrdinalConstants)
        {
            sb.AppendLine("    // Column ordinals");
            for (var i = 0; i < model.Columns.Count; i++)
                sb.Append("    private const int Ord").Append(Capitalize(model.Columns[i].Name))
                    .Append(" = ").Append(model.Columns[i].OrdinalPosition).AppendLine(";");
            sb.AppendLine();
        }

        sb.AppendLine(
            "    /// <summary>Maps a single row from the <see cref=\"SqlDataReader\"/> into a new instance.</summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine(
            $"    [GeneratedCode(\"{GeneratedCodeInfo.ToolName}\", \"{GeneratedCodeInfo.Version}\")]");
        sb.Append("    public static ").Append(model.TypeName).AppendLine(" MapFromDataReader(SqlDataReader reader)");
        sb.AppendLine("    {");
        sb.Append("        return new ").Append(model.TypeName).AppendLine("(");

        for (var i = 0; i < model.Columns.Count; i++)
        {
            var column = model.Columns[i];
            var trailing = i < model.Columns.Count - 1 ? "," : string.Empty;
            sb.Append("            ").Append(BuildReaderExpression(column, useOrdinalConstants)).AppendLine(trailing);
        }

        sb.AppendLine("        );");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    ///     Builds the <c>SqlDataReader</c> expression for a single column. The classification was performed
    ///     during extraction (<see cref="ColumnKind" />), so this method is a pure switch on data — no string
    ///     guessing, no <c>Contains</c>.
    /// </summary>
    private static string BuildReaderExpression(ColumnModel column, bool useOrdinalConstants)
    {
        var ordinal = useOrdinalConstants
            ? "Ord" + Capitalize(column.Name)
            : column.OrdinalPosition.ToString();
        var prefix = column.IsNullable ? $"reader.IsDBNull({ordinal}) ? null : " : string.Empty;

        return column.Kind switch
        {
            ColumnKind.ByteArray => $"{prefix}reader.GetFieldValue<byte[]>({ordinal})",
            ColumnKind.DateOnly => $"{prefix}DateOnly.FromDateTime(reader.GetDateTime({ordinal}))",
            ColumnKind.TimeOnly => $"{prefix}TimeOnly.FromDateTime(reader.GetDateTime({ordinal}))",
            ColumnKind.Char => $"{prefix}reader.GetString({ordinal})[0]",
            ColumnKind.Half => $"{prefix}(Half)reader.GetFloat({ordinal})",
            ColumnKind.Enum => $"{prefix}({column.TypeName.TrimEnd('?')})reader.{column.ReaderMethod}({ordinal})",
            _ => $"{prefix}reader.{column.ReaderMethod}({ordinal})"
        };
    }

    /// <summary>Capitalizes the first character of a parameter name for use in ordinal constant names.</summary>
    private static string Capitalize(string name)
    {
        if (string.IsNullOrEmpty(name) || char.IsUpper(name[0])) return name;
        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }
}
