global using System;
global using System.Collections.Immutable;
global using System.Collections.Generic;
global using System.Linq;
global using CaeriusNet.Analyzer.Tests.Utilities;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.Diagnostics;
global using Xunit;