namespace CaeriusNet.Generator.MultiResults;

internal static class MultiResultSetSignaturesEmitter
{
    internal static SourceText Emit()
    {
        var sb = new StringBuilder(32_768);

        AppendHeader(sb);
        AppendUsings(sb);
        sb.AppendLine("namespace CaeriusNet.Commands.Reads;");
        sb.AppendLine();

        AppendFamily(sb, "GeneratedMultiIEnumerableReadSqlAsyncCommands", "QueryMultipleIEnumerableAsync",
            "IEnumerable", ResultShape.Enumerable);
        AppendFamily(sb, "GeneratedMultiReadOnlyCollectionReadSqlAsyncCommands", "QueryMultipleReadOnlyCollectionAsync",
            "ReadOnlyCollection", ResultShape.ReadOnlyCollection);
        AppendFamily(sb, "GeneratedMultiImmutableArrayReadSqlAsyncCommands", "QueryMultipleImmutableArrayAsync",
            "ImmutableArray", ResultShape.ImmutableArray);

        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated by CaeriusNet.Generator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        sb.AppendLine();
    }

    private static void AppendUsings(StringBuilder sb)
    {
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine("using System.Collections.ObjectModel;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CaeriusNet.Abstractions;");
        sb.AppendLine("using CaeriusNet.Helpers;");
        sb.AppendLine("using CaeriusNet.Mappers;");
        sb.AppendLine("using CaeriusNet.Telemetry;");
        sb.AppendLine();
    }

    private static void AppendFamily(
        StringBuilder sb,
        string className,
        string methodName,
        string collectionType,
        ResultShape shape)
    {
        sb.Append("public static class ").Append(className).AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("    extension(ICaeriusNetDbContext context)");
        sb.AppendLine("    {");

        for (var arity = 3; arity <= 5; arity++)
        {
            AppendMethod(sb, methodName, collectionType, shape, arity);
            if (arity < 5)
                sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendMethod(
        StringBuilder sb,
        string methodName,
        string collectionType,
        ResultShape shape,
        int arity)
    {
        var typeParameters = BuildTypeParameters(arity);

        sb.AppendLine("        /// <summary>");
        sb.Append("        ///     Execute a stored procedure and materialize up to ")
            .Append(arity)
            .Append(" result sets as ")
            .Append(GetCollectionDescription(shape))
            .AppendLine(".");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"spParameters\">Stored procedure metadata and parameters.</param>");
        sb.AppendLine("        /// <param name=\"cancellationToken\">Token to cancel the operation.</param>");
        sb.AppendLine("        /// <returns>A tuple containing the materialized result sets. Missing trailing result sets are empty.</returns>");
        AppendGeneratedCodeAttribute(sb, "        ");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveOptimization)]");
        sb.Append("        public ValueTask<(").Append(BuildTupleType(collectionType, arity)).AppendLine(")>");
        sb.Append("            ").Append(methodName).Append('<').Append(typeParameters).AppendLine(">(");
        sb.AppendLine("                StoredProcedureParameters spParameters,");
        sb.AppendLine("                CancellationToken cancellationToken = default)");
        AppendConstraints(sb, arity);
        sb.AppendLine("        {");
        sb.Append("            return CaeriusActivityExtensions.InstrumentMultiResultSetAsync<(")
            .Append(BuildTupleType(collectionType, arity))
            .Append(")>(context, spParameters, ")
            .Append(arity)
            .AppendLine(",");
        sb.Append("                nameof(").Append(methodName).AppendLine("), async command =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    await using var reader = await command.ExecuteReaderAsync(");
        sb.AppendLine("                        CommandBehavior.SequentialAccess, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine();

        for (var index = 1; index <= arity; index++)
        {
            if (index > 1)
            {
                sb.AppendLine("                    if (!await MultiResultSetHelper.TryMoveNextAsync(reader, cancellationToken).ConfigureAwait(false))");
                sb.Append("                        return (").Append(BuildReturnTuple(shape, arity, index - 1)).AppendLine(");");
                sb.AppendLine();
            }

            AppendReadResultSet(sb, shape, index);
            if (index < arity)
                sb.AppendLine();
        }

        sb.AppendLine();
        sb.Append("                    return (").Append(BuildReturnTuple(shape, arity, arity)).AppendLine(");");
        sb.AppendLine("                }, cancellationToken);");
        sb.AppendLine("        }");
    }

    private static void AppendGeneratedCodeAttribute(StringBuilder sb, string indent)
    {
        sb.Append(indent)
            .Append("[GeneratedCode(\"")
            .Append(GeneratedCodeInfo.ToolName)
            .Append("\", \"")
            .Append(GeneratedCodeInfo.Version)
            .AppendLine("\")]");
    }

    private static void AppendReadResultSet(StringBuilder sb, ResultShape shape, int index)
    {
        var typeName = "TResultSet" + index;
        var resultName = GetResultName(shape, index);

        if (shape == ResultShape.ImmutableArray)
        {
            sb.Append("                    var ").Append(resultName)
                .Append(" = await MultiResultSetHelper.ReadResultSetAsImmutableArrayAsync<")
                .Append(typeName)
                .AppendLine(">(");
            sb.AppendLine("                        reader, spParameters.Capacity, cancellationToken).ConfigureAwait(false);");
            return;
        }

        sb.Append("                    var l").Append(index)
            .Append(" = await MultiResultSetHelper.ReadResultSetAsync<")
            .Append(typeName)
            .AppendLine(">(");
        sb.AppendLine("                        reader, spParameters.Capacity, cancellationToken).ConfigureAwait(false);");

        if (shape == ResultShape.ReadOnlyCollection)
            sb.Append("                    var ").Append(resultName).Append(" = l").Append(index).AppendLine(".AsReadOnly();");
    }

    private static void AppendConstraints(StringBuilder sb, int arity)
    {
        for (var i = 1; i <= arity; i++)
            sb.Append("            where TResultSet")
                .Append(i)
                .Append(" : class, ISpMapper<TResultSet")
                .Append(i)
                .AppendLine(">");
    }

    private static string BuildTupleType(string collectionType, int arity)
    {
        var sb = new StringBuilder(arity * 36);
        for (var i = 1; i <= arity; i++)
        {
            if (i > 1)
                sb.Append(", ");
            sb.Append(collectionType).Append("<TResultSet").Append(i).Append('>');
        }

        return sb.ToString();
    }

    private static string BuildTypeParameters(int arity)
    {
        var sb = new StringBuilder(arity * 12);
        for (var i = 1; i <= arity; i++)
        {
            if (i > 1)
                sb.Append(", ");
            sb.Append("TResultSet").Append(i);
        }

        return sb.ToString();
    }

    private static string BuildReturnTuple(ResultShape shape, int arity, int populated)
    {
        var sb = new StringBuilder(arity * 12);
        for (var i = 1; i <= arity; i++)
        {
            if (i > 1)
                sb.Append(", ");
            sb.Append(i <= populated ? GetResultName(shape, i) : GetEmptyExpression(shape, i));
        }

        return sb.ToString();
    }

    private static string GetResultName(ResultShape shape, int index)
    {
        switch (shape)
        {
            case ResultShape.Enumerable:
                return "l" + index;
            case ResultShape.ReadOnlyCollection:
                return "r" + index;
            case ResultShape.ImmutableArray:
                return "a" + index;
            default:
                throw new ArgumentOutOfRangeException(nameof(shape), shape, null);
        }
    }

    private static string GetEmptyExpression(ResultShape shape, int index)
    {
        switch (shape)
        {
            case ResultShape.ImmutableArray:
                return "ImmutableArray<TResultSet" + index + ">.Empty";
            default:
                return "[]";
        }
    }

    private static string GetCollectionDescription(ResultShape shape)
    {
        switch (shape)
        {
            case ResultShape.Enumerable:
                return "enumerable sequences";
            case ResultShape.ReadOnlyCollection:
                return "read-only collections";
            case ResultShape.ImmutableArray:
                return "immutable arrays";
            default:
                throw new ArgumentOutOfRangeException(nameof(shape), shape, null);
        }
    }

    private enum ResultShape
    {
        Enumerable,
        ReadOnlyCollection,
        ImmutableArray
    }
}
